development:
  database:
    name: nuca
    host: ds037611.mongolab.com
    port: 37611
    username: nuca
    password: nuca123

test:
  database:
    name: nuca-server_test
    host: 127.0.0.1
    port: 27017

production:
  database:
    name: nuca-server
    host: 127.0.0.1
    port: 27017
