development:
  database:
    name: nuca-server_development
    host: 127.0.0.1
    port: 27017

test:
  database:
    name: nuca-server_test
    host: 127.0.0.1
    port: 27017

production:
  database:
    name: nuca-server
    host: 127.0.0.1
    port: 27017
